apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name:  {{ template "todo.fullname" . }}
  labels:
{{ include "todo.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image | quote }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ENABLE_COMPLETED_FILTER
          value: "{{ .Values.env.enableCompletedFilter }}"
        - name: ENABLE_OVERDUE_FILTER
          value: "{{ .Values.env.enableOverdueFilter }}"
        - name: UPGRADE_LINK
          value: "{{ .Values.env.upgradeLink }}"
{{- if hasKey .Values "subscription" }}
        - name: TENANT_NAME
          value: '{{ .Values.subscription.tenantobj.name }}'
        - name: TENANT_ID
          value: '{{ .Values.subscription.tenant }}'
{{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
