apiVersion: v1
kind: Service
metadata:
  name: {{ template "todo.fullname" . }}
  labels:
{{ include "todo.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.externalPort | int }}
      targetPort: {{ .Values.service.internalPort | int }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "todo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
