apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ .Chart.Name }}-service
spec:
  ports:
    - port: {{ .Values.service.externalPort | int }}
      targetPort: {{ .Values.service.internalPort | int }}
      protocol: TCP
  selector:
    app: {{ $fullname }}
