# Requires two secrets to be configured:
# GITLAB_PAT to access GitLab to pull gitlab.com/caspr-io/root
# DOCKER_HUB_PAT to push the Docker image to the Docker Hub

name: Build and push Docker image for Todo app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Checkout caspr-io/root from GitLab
        run: git clone https://gitlab-ci-token:${GITLAB_PAT}@gitlab.com/caspr-io/root ../root
        env:
          GITLAB_PAT: ${{secrets.GITLAB_PAT}}

      - name: Build Docker image
        run: make build

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: vpartington
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Push Docker image
        run: make docker/push
