name: Todo app CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Checkout caspr-io/root from GitLab
        run: git clone https://gitlab-ci-token:${GITLAB_PAT}@gitlab.com/caspr-io/root ../root
        env:
          GITLAB_PAT: ${{secrets.GITLAB_PAT}}

      # - name: Ensure can write in repo
      #   run: chmod ugo+w -R pkg
      - name: Build Docker image
        run: make build

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: vpartington
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Push Docker image
        run: make docker/push
